import { getCookie } from 'cookies-next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <a href='/api/twitch'>Login with Twitch</a>
    </div>
  );
}

export const getServerSideProps = async ({ req, res }) => {
  try {
    const cookieExists = getCookie('token', { req, res });
    if (cookieExists) {
      return { redirect: { destination: '/dashboard' } };
    }
    return { props: {} };
  } catch (err) {
    return { props: {} };
  }
};
